### ISSUE TITLE
Create missing behavioural design patterns: Memento, State, Visitor

### ISSUE THREAD

**Issue by veelenga** [veelenga/crystal-patterns#10]
Add the following behavioural patterns:

* [Memento](http://www.blackwasp.co.uk/Memento.aspx)
* [State](http://www.blackwasp.co.uk/State.aspx)
* [Visitor](http://www.blackwasp.co.uk/Visitor.aspx)

Keep in mind, that implementation is thematic, so somehow it should relate to the popular [Mortal Kombat](http://mortalkombat.wikia.com/wiki/Mortal_Kombat_Wiki) or video games in general. You may found some ideas in existed implementations... 

*Note:* before you start, [install Crystal programming language](https://crystal-lang.org/docs/installation/).

**Comment by silverweed** [comment]
Adding Memento pattern in https://github.com/crystal-community/crystal-patterns/pull/11

**Comment by silverweed** [comment]
Adding Visitor pattern in #12
