### ISSUE TITLE
Layman terms of each design patterns

### ISSUE THREAD

**Issue by proyb6** [veelenga/crystal-patterns#17]
It’s useful if we have an easier to understand comparisons chart that make it easier and know when to apply in certain projects?

**Comment by veelenga** [comment]
Could you share an example?

**Comment by proyb6** [comment]
I mean like a table charts with each scenarios how we can share data across modules or classes, which is useful for large vs small code base, which is easier and complex.

**Comment by veelenga** [comment]
I don't see any reason not to do that. Do you want to give it a try?

**Comment by proyb6** [comment]
Great, but I’m still new to Crystal and design patterns. Perhaps, I’ll let the pros have a go.

**Comment by veelenga** [comment]
I don't have any interest and time to do this. If someone is willing working on it, please go head.
