### ISSUE TITLE
Create missing structural design patterns

### ISSUE THREAD

**Issue by veelenga** [veelenga/crystal-patterns#4]
Currently [there are](https://github.com/veelenga/crystal-patterns/tree/master/structural) adapter, bridge, composite and decorator.

To finish the [list of structural patterns](http://www.blackwasp.co.uk/gofpatterns.aspx) the following should be added:

* [Facade](http://www.blackwasp.co.uk/Facade.aspx) 
* [Flyweight](http://www.blackwasp.co.uk/Flyweight.aspx)
* [Proxy](http://www.blackwasp.co.uk/Proxy.aspx)

Keep in mind, that implementation is thematic, so somehow it should relate to the popular [Mortal Kombat game](http://mortalkombat.wikia.com/wiki/Mortal_Kombat_Wiki). You may found some ideas in existed implementations... 

*Note:* before you start, [install Crystal programming language](https://crystal-lang.org/docs/installation/).

**Comment by silverweed** [comment]
I'm willing to contribute to this issue, do you prefer separate pull requests for each patterns or a single one?

**Comment by veelenga** [comment]
Great 👍  It's up to you!

**Comment by silverweed** [comment]
Good :)
I think I'll keep them separate to ease reviewing then.

**Comment by veelenga** [comment]
Nice job, thanks a lot. I have added you to the list of contributors 9de5a04e19b04fb6f238a0c33ac26b68d60ab2ef

Are you interested in working on missing behavioural patterns? I am going to create two separate issues for this with hacktoberfest label.

**Comment by silverweed** [comment]
Why not? I enjoy writing crystal :)

**Comment by veelenga** [comment]
Great, checkout #9 and #10. You may need to leave a comment so anyone else will not ask about assignment.  

I added you to the collaborators, so please create branches directly on this repo, not on the fork.
