### ISSUE TITLE
Create missing behavioural design patterns: ChainOfResponsibility, Interpreter, Mediator

### ISSUE THREAD

**Issue by veelenga** [veelenga/crystal-patterns#9]
Add the following behavioural patterns:

 - [x] [ChainOfResponsibility](http://www.blackwasp.co.uk/ChainOfResponsibility.aspx)
 - [ ] [Interpreter](http://www.blackwasp.co.uk/Interpreter.aspx)
 - [x] [Mediator](http://www.blackwasp.co.uk/Mediator.aspx)

Keep in mind, that implementation is thematic, so somehow it should relate to the popular [Mortal Kombat](http://mortalkombat.wikia.com/wiki/Mortal_Kombat_Wiki) or video games in general. You may found some ideas in existed implementations... 

*Note:* before you start, [install Crystal programming language](https://crystal-lang.org/docs/installation/).

**Comment by anicholson** [comment]
I'm going to give this a crack. @veelenga would you prefer 1 PR with all 3, or are separate PRs okay?

**Comment by veelenga** [comment]
Cool! It is up to you
